### PR TITLE
add coursersa link to readme to check links

### PR DESCRIPTION
**Pull request by kweav**
Want to check links, so made a token change to the README file (specifically added the coursera link for the course).

### CODE REVIEW

**Comment by kweav** [comment]
After [commit a4dfb7f](https://github.com/jhudsl/Documentation_and_Usability/pull/117/commits/a4dfb7f39e5e972e5a1ccd6f43e0d42df22074dd) the preview rendered successfully. Double checked that the slides matched the content on the current bookdown. The title now includes ITCR in the very first slide, and there are a few slides with aesthetic rearrangements/differences, but the content is the same. 

The spell check is still failing so I'll try to push edits to those too.

**Comment by kweav** [comment]
This url needs to be replaced: https://github.com/jhudsl/Documentation_and_Usability/blob/main/.github/workflows/url-checker.yml. But I'm not sure what to replace it with. The rest being flagged, when copy/pasted in my browser, work.

**Comment by carriewright11** [comment]
> This url needs to be replaced: https://github.com/jhudsl/Documentation_and_Usability/blob/main/.github/workflows/url-checker.yml. But I'm not sure what to replace it with. The rest being flagged, when copy/pasted in my browser, work.

we can push a synch from the template to here... but this is an old repo, one of the first... so @cansavvy maybe you should take a deeper look

**Comment by carriewright11** [comment]
This looks good though besides the change in the index file for the link to the slides. Thank you very much for doing this. Could you also add yourself to the about page for these efforts... maybe as "Content Publishing Reviewers"? What do you think @cansavvy ?

**Comment by carriewright11** [comment]
LGTM! the urls seem to be an artifact of maybe the newest version being still picky about parentheses etc.

**Comment by kweav** [comment]
> This url needs to be replaced: https://github.com/jhudsl/Documentation_and_Usability/blob/main/.github/workflows/url-checker.yml. But I'm not sure what to replace it with. The rest being flagged, when copy/pasted in my browser, work.

@cansavvy Is this link from the OTTR Template a good link to switch out for this broken URL? https://github.com/jhudsl/OTTR_Template/blob/main/.github/workflows/check-url.yml

**Comment by cansavvy** [comment]
> https://github.com/jhudsl/OTTR_Template/blob/main/.github/workflows/check-url.yml

Yes that works. Thanks!

**Comment by kweav** [comment]
Good to merge now? @cansavvy and @carriewright11 ?

**Review by cansavvy — APPROVED** [review]
Thanks for this @kweav !!! Super necessary and long overdue.

**Pull request merged**
